language: node_js

node_js:
  - "node"

before_script:
  - yarn

script:
  - yarn build
  - yarn export

after_success:
  - touch ./out/.nojekyll

env:
  - NEXT_ENV=production

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
